### ISSUE TITLE
FFだとgenerateボタン押下後、フォームが空になる

### ISSUE THREAD

**Issue by eeeeerika** [kyuuuuuji/next-next#1]
* 原因っぽいもの
    * https://stackoverflow.com/questions/20522887/referenceerror-event-is-not-defined-error-in-firefox

**Comment by kyuuuuuji** [comment]
pull request作成
https://github.com/kyuuuuuji/next-next/pull/2

**Comment by kyuuuuuji** [comment]
デプロイ後動作確認しました。
ご確認いただいて問題なければcloseいたします。

**Comment by eeeeerika** [comment]
お疲れ様です。対応ありがとうございます。
こちらでも動作確認できました。対応頂いた内容で問題ないかと思います。
本issueのcloseをお願いします。
